### ISSUE TITLE
🔌  Links

### ISSUE THREAD

**Issue by sarahyjja** [fac18/khol#62]
Where are your links?
You can add them very easily and quickly in your html.
This is a 5 min issue :)

**Comment by plasticneuron** [comment]
Links look really nice but I also noticed that although they have aria labels describing which site they link to, they don't say who's profile it will be.

You seem to have included this information in alt properties in the relevant <a> tags, but these don't take alt text so it isn't being read out by my screen reader (it might work on the Codewars svg's since these are graphical elements, but it's still on the anchor tags in these cases too).

**Comment by redahaq** [comment]
It's lovely that you've added styling for the :hover state of your codewars icons, turning the logo green. 👍

- It would be nice to see the same thing applied to the github and linkedin icons as well, for consistency.

**Comment by bethanyios** [comment]
Really love these profile cards - very nice design

Minor additions to link related issue: the hover over Nikke's codewars icon is the same colour as the background which could cause accessibility problems. I like the green colour but maybe a white/pale pink would avoid the issue.

I would also suggest adjusting the padding above the Team title so that the profiles would be more centred in this section. 

Simple design overall making it look really professional and I love the colour palette 💃🏽
